name: Test

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Build
        run: docker buildx build . -o dist

      - name: Test
        run: ./dist/cabal-fmt --version

      - name: Prepare archive
        run: tar -zcvf ./${{ matrix.os }}.tar.gz -C dist cabal-fmt

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-binary
          path: ${{ matrix.os }}.tar.gz
